server:
  port: 8080

spring:
  application:
    name: URL-Shortening-Service
  datasource:
    url: jdbc:postgresql://localhost:<postgresql-port>/<database-name>
    username: <your-username>
    password: <your_password>
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true